import { UserData } from './types'

export const mockUserData: UserData[] = [
  {
    id: '4634433',
    online: true,
    botStatus: true,
    accountId: '4634433',
    name: 'John Doe',
    email: 'john@example.com',
    group: 'Whatsapp.',
    referral: 'REF001',
    leverage: 100,
    balance: 0.00,
    equity: 0.00,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.00,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
  {
    id: '4558575',
    online: false,
    botStatus: false,
    accountId: '4558575',
    name: 'Jane Smith',
    email: 'jane@example.com',
    group: 'DefaultGro',
    referral: 'REF002',
    leverage: 100,
    balance: 20.09,
    equity: 20.09,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.09,
    botProfit: 0.05,
    botSetting: 'Whatsapp_Group_set',
    botSubscription: true,
    botEnabled: true,
    showBotSettings: true,
  },
  {
    id: '4634434',
    online: true,
    botStatus: true,
    accountId: '4634434',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    group: 'Whatsapp.',
    referral: 'REF003',
    leverage: 100,
    balance: 120.48,
    equity: 120.48,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.48,
    botProfit: 0.17,
    botSetting: 'B_B',
    botSubscription: false,
    botEnabled: true,
    showBotSettings: false,
  },
  {
    id: '4558576',
    online: false,
    botStatus: false,
    accountId: '4558576',
    name: 'Sarah Wilson',
    email: 'sarah@example.com',
    group: 'DefaultGro',
    referral: 'REF004',
    leverage: 100,
    balance: 7159.62,
    equity: 7159.62,
    marginLevel: 99996.22,
    unrealizedPnL: 0.00,
    realizedPnL: 2159.62,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
  {
    id: '4634435',
    online: true,
    botStatus: true,
    accountId: '4634435',
    name: 'David Brown',
    email: 'david@example.com',
    group: 'Whatsapp.',
    referral: 'REF005',
    leverage: 100,
    balance: 1058.22,
    equity: 1315.09,
    marginLevel: 2481.30,
    unrealizedPnL: 256.87,
    realizedPnL: 38.22,
    botProfit: 2.08,
    botSetting: 'B_B',
    botSubscription: true,
    botEnabled: true,
    showBotSettings: true,
  },
  {
    id: '4558577',
    online: false,
    botStatus: false,
    accountId: '4558577',
    name: 'Lisa Davis',
    email: 'lisa@example.com',
    group: 'DefaultGro',
    referral: 'REF006',
    leverage: 100,
    balance: 0.00,
    equity: 0.00,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: -1559.41,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
  {
    id: '4634436',
    online: true,
    botStatus: true,
    accountId: '4634436',
    name: 'Tom Miller',
    email: 'tom@example.com',
    group: 'Whatsapp.',
    referral: 'REF007',
    leverage: 100,
    balance: 0.00,
    equity: 0.00,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.00,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
  {
    id: '4558578',
    online: false,
    botStatus: false,
    accountId: '4558578',
    name: 'Emma Garcia',
    email: 'emma@example.com',
    group: 'DefaultGro',
    referral: 'REF008',
    leverage: 100,
    balance: 0.00,
    equity: 0.00,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.00,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
  {
    id: '4634437',
    online: true,
    botStatus: true,
    accountId: '4634437',
    name: 'Chris Lee',
    email: 'chris@example.com',
    group: 'Whatsapp.',
    referral: 'REF009',
    leverage: 100,
    balance: 0.00,
    equity: 0.00,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.00,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
  {
    id: '4558579',
    online: false,
    botStatus: false,
    accountId: '4558579',
    name: 'Anna White',
    email: 'anna@example.com',
    group: 'DefaultGro',
    referral: 'REF010',
    leverage: 100,
    balance: 0.00,
    equity: 0.00,
    marginLevel: 0.00,
    unrealizedPnL: 0.00,
    realizedPnL: 0.00,
    botProfit: 0.00,
    botSetting: '---',
    botSubscription: false,
    botEnabled: false,
    showBotSettings: false,
  },
]

export const COLUMN_CONFIGS = {
  FINANCIAL_COLUMNS: ['balance', 'equity', 'unrealizedPnL', 'realizedPnL', 'botProfit'],
  USER_COLUMNS: ['name', 'email', 'accountId'],
  STATUS_COLUMNS: ['online', 'botStatus', 'botSubscription', 'botEnabled', 'showBotSettings'],
  GROUP_OPTIONS: ['Whatsapp.', 'DefaultGro'],
  PAGE_SIZE_OPTIONS: [10, 20, 30, 40, 50],
} as const 